name: Build and Verify - Multiplatform Sample

on:
  workflow_dispatch:
#  pull_request:

jobs:
  build-verify-multiplatform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build And Verify - Multiplatform Sample
        run: |
          chmod +x .github/scripts/build-verify-multiplatform.sh
          .github/scripts/build-verify-multiplatform.sh
