name: Build and Verify - Android Sample

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-verify-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build And Verify - Multiplatform Sample
        run: |
          chmod +x .github/scripts/build-verify-android.sh
          .github/scripts/build-verify-android.sh