name: Build and Verify - Android Sample

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-verify-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Gradle Sync
        run: ./gradlew --refresh-dependencies

      - name: Remove All Android Components from sample-android
        run: |
          rm -rf sample-android/ui-components/src/main/java/com/nomanr/sample/ui/foundation
          rm -rf sample-android/ui-components/src/main/java/com/nomanr/sample/ui/components

      - name: Add lumo.properties
        run: |
          rm -rf lumo.properties
          cat <<EOF > lumo.properties
          ThemeName=AppTheme

          ComponentsDir=sample-android/ui-components/src/main/java/com/nomanr/sample/ui
          PackageName=com.nomanr.sample.ui
          EOF

      - name: Generate All Components in sample-android
        run: ./gradlew lumo --addAll

      - name: Build sample-android
        run: ./gradlew sample-android:catalogue:assembleDebug