name: Download and Build KMP Starter Project

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-verify-kmp-starter-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download and Build KMP Starter Project
        run: |
          chmod +x .github/scripts/download-build-kmp-starter-project.sh
          .github/scripts/download-build-kmp-starter-project.sh "0.0.1-SNAPSHOT"
