name: Upload Build to Deploy branch

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  upload-build-to-deploy-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch (where PR is being updated)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

#      - name: Build And Verify - Multiplatform Sample
#        run: |
#          chmod +x .github/scripts/build-verify-multiplatform.sh
#          .github/scripts/build-verify-multiplatform.sh

      - name: Git user configs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Switch to deploy branch and force merge main
        run: |
          git fetch origin
          git checkout -b deploy
          git reset --hard origin/main

      - name: Build Sample
        run: |
          ./gradlew :sample-multiplatform:catalogue:web:wasmJsBrowserDistribution

      - name: Move dist to root/docs
        run: |
          DOCS_DIR=docs
          BUILD_DIR=sample-multiplatform/catalogue/web/build/dist/wasmJs/productionExecutable

          rm -rf $DOCS_DIR
          mkdir -p $DOCS_DIR

          mv $BUILD_DIR/* $DOCS_DIR/

      - name: Force push changes to deploy branch
        run: |
          git add docs
          git commit -m "Deploy to github pages"
          git push --force origin deploy